version: '{build}'
environment:
  nodejs_version: "Stable"
matrix:
  fast_finish: true
  
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install && npm install karma-ie-launcher
  - npm install -g @angular/cli@latest
  
build_script:
- npm install
- ng build --no-progress --no-verbose
test_script:
- ng test --watch=false --code-coverage --no-progress --no-verbose
- ng lint